apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quiet-core-bot-home-pvc
  labels:
    app: quiet-core-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
